name: Insecure Workflow
on: push
jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@latest  # Użycie "latest" zamiast konkretnego SHA

      - name: Print secret
        run: echo "API_KEY=${{ secrets.API_KEY }}"
